###### 2020-08-02

---
#### 예외처리

[8-1] 예외처리의 정의와 목적에 대해서 설명하시오.
정의: 프로그램 실행 시 발생할 수 있는 예외를 처리하는것으로 프로그램의 비정상적인 종료를 막는일
에러보다 상대적으로 덜 중요한 오류에 사용  
목적: 프로그램의 비정상적인 종료를 막고, 바른 방향으로 프로그램을 수행되게 하는 목적

[8-2] 다음은 실행도중 예외가 발생하여 화면에 출력된 내용이다 이에 대한 설명 중 옳 . 지 않은 것은? d 
```
java.lang.ArithmeticException : / by zero
    at ExceptionEx18.method2(ExceptionEx18.java:12)
    at ExceptionEx18.method1(ExceptionEx18.java:8)
    at ExceptionEx18.main(ExceptionEx18.java:4)
```
a. 위의 내용으로 예외가 발생했을 당시 호출스택에 존재했던 메서드를 알 수 있다.
b. 예외가 발생한 위치는 method2 메서드이며, ExceptionEx18.java파일의 12번째 줄이다.
c. 발생한 예외는 ArithmeticException이며, 0으로 나누어서 예외가 발생했다.
d. method2메서드가 method1메서드를 호출하였고 그 위치는 ExceptionEx18.java파일의 8번째 줄이다.

[8-4] 다음과 같은 메서드가 있을 때, 예외를 잘못 처리한 것은? (모두 고르시오) a e f
```
void method() throws InvalidNumberException, NotANumberException {}
class NumberException extends RuntimeException {}
class InvalidNumberException extends NumberException {}
class NotANumberException extends NumberException {}
```
a. try {method();} catch(Exception e) {}
b. try {method();} catch(NumberException e) {} catch(Exception e) {}
c. try {method();} catch(Exception e) {} catch(NumberException e) {}
d. try {method();} catch(InvalidNumberException e) {} catch(NotANumberException e) {}
e. try {method();} catch(NumberException e) {}
f. try {method();} catch(RuntimeException e) {}

[8-8] 다음은 1~100사이의 숫자를 맞추는 게임을 실행하던 도중에 숫자가 아닌 영문자를넣어서 발생한 예외이다.
예외처리를 해서 숫자가 아닌 값을 입력했을 때는 다시 입력을 받도록 보완하라.

##### Coding
##### 실행 결과
```

1과 100사이의 값을 입력하세요 :50
더 작은 수를 입력하세요.
1과 100사이의 값을 입력하세요 :asdf
유효하지 않은 값입니다. 다시 값을 입력해주세요.
1과 100사이의 값을 입력하세요 :25
더 큰 수를 입력하세요.
1과 100사이의 값을 입력하세요 :38
더 큰 수를 입력하세요.
1과 100사이의 값을 입력하세요 :44
맞췄습니다.
시도횟수는 5번입니다.
```

[8-9] 다음과 같은 조건의 예외클래스를 작성하고 테스트하시오.
[참고] 생성자는 실행결과를 보고 알맞게 작성해야한다.
* 클래스명 : UnsupportedFuctionException
* 조상클래스명 : RuntimeException
* 멤버변수 :
이 름 : ERR_CODE
저장값 : 에러코드
타 입 : int
기본값 : 100
제어자 : final private
* 메서드 :
1. 메서드명 : getErrorCode
기 능 : 에러코드(ERR_CODE)를 반환한다.
반환타입 : int
매개변수 : 없음
제어자 : public
2. 메서드명 : getMessage
기 능 : 메세지의 내용을 반환한다.(Exception클래스의 getMessage()를 오버라이딩)
반환타입 : String
매개변수 : 없음
제어자 : public

##### coding
##### 실행결과
```
Exception in thread "main" UnsupportedFuctionException: [100]지원하지 않는 기능입니다.
at Exercise8_9.main(Exercise8_9.java:5)
```

[MakeExercise] 다음 결과에 맞춰 빈 칸을 채우시오.

##### coding
##### 실행결과
```
input boolean value [ true | false ] : true
Start
throw Test : IllegalAccessException of Sub Method
throw Test : IllegalAccessException of Main Method

...

input boolean value [ true | false ] : false
Start
throw Test : NullPointerException of Sub Method
throw Test : NullPointerException of Main Method

```

---

#### 유효한 클래스

[9-1] 다음과 같은 실행결과를 얻도록 SutdaCard클래스의 equals()를 멤버변수인 num, isKwang의 값을 비교하도록 오버라이딩하고 테스트 하시오.

##### coding
##### 실행결과
```
c1=3K
c2=3K
c1.equals(c2):true
```

[9-7] 다음과 같이 정의된 메서드를 작성하고 테스트하시오.
메서드명 : contains
기 능 : 첫 번째 문자열(src)에 두 번째 문자열(target)이 포함되어 있는지 확인한다.
포함되어 있으면 true, 그렇지 않으면 false를 반환한다.
반환타입 : boolean
매개변수 : String src
String target
[Hint] String클래스의 indexOf()를 사용할 것

##### coding
##### 실행결과
```
true
false
```

[9-13] 다음은 하나의 긴 문자열(source) 중에서 특정 문자열과 일치하는 문자열의 개수를 구하는 예제이다. 빈 곳을 채워 예제를 완성하시오.


##### coding
##### 실행결과
```
true
false
```